service: homeloaf-be
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentMethod: direct
  region: us-west-2
  stage: production
  memorySize: 512
  timeout: 10
  environment:
    OPENAI_KEY: ${param:OPENAI_KEY}

functions:
  test:
    handler: test.handler
